services:
  uni-policy-agent:
    image: uni-policy-agent:v1
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7860:7860"
    volumes:
      - ./policy_links.json:/app/policy_links.json
      - ./vectorstore_index:/app/vectorstore_index
    env_file:
      - .env
    restart: unless-stopped
